name: Generate Snake Game

on:
  schedule:
    # Schedule to run the action every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:
    # This allows you to run this action manually from the Actions tab

jobs:
  build:
    name: Generate Snake Game from Contributions
    runs-on: ubuntu-latest # Specifies the runner

    steps:
      # Checkout your repository
      - uses: actions/checkout@v2

      # Generate the snake game
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Here you specify the output SVG path
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy the generated SVG to a specific branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # Target branch to which the SVG should be pushed
          target_branch: output
          # Directory where the SVG is located
          build_dir: dist
        env:
          # The GitHub Token is used for authentication with GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
